### ISSUE TITLE
the method 'of' in class org.raistlic.common.permutation.Factorial  has a big bug in release 1.3

### ISSUE THREAD

**Issue by ghost** [raistlic/raistlic-lib-commons-core#2]
the method 'of' in class org.raistlic.common.permutation.Factorial  has a big bug in release 1.3, I see this bug was fixed in master brach, why not release a new version?

**Comment by raistlic** [comment]
hi liufw, sorry for the late response.
I was just being lazy & not enough motivation to maintain this little lib, now the more I use it myself, the more I realize it's such a pain to use a snapshot from my maven local as I frequently move from one machine to another...
anyways, 1.4 released, please keep telling me when you find new bugs.

thanks again.
lei
